### ISSUE TITLE
ImportError: cannot import name 'utils' from 'matcha'

### ISSUE THREAD

**Issue by Shazzum** [shivammehta25/Matcha-TTS#107]
I am trying to train my own dataset. I keep getting this error message when I run python matcha/train.py experiment=ljspeech . Anyone know how to fix this?

**Comment by shivammehta25** [comment]
Did you do 'pip install -e .'?

**Comment by Shazzum** [comment]
Sorry to bother, I am very new to coding. when I did that, it gave me this message.

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument

**Comment by shivammehta25** [comment]
Just put a dot/period/point at the end '.'

**Comment by Shazzum** [comment]
Ok! Thank you so much for your help! I put a period on the end this time, and I think it successfully installed '-e.' However, now when i run 'python matcha/train.py experiment=ljspeech' I am still getting the error 'ImportError: cannot import name 'utils' from 'matcha''
What am I doing wrong?

**Comment by Shazzum** [comment]
I am trying to resolve this issue, but I cannot seem to figure out how. I want to train the model on the libritts dataset and I think I am preparing the files directly. I am trying to follow the instructions on the main page, but I am still having this issue. Please let me know if you have any suggestions. Thanks!

**Comment by shivammehta25** [comment]
Could you share the exact command and screenshot that you've used? It should have been working at this point. Can you make sure that you are in the correct environment?

**Comment by Shazzum** [comment]
issue is solved. The matcha.py file was causing issues because it had the same name as the folder
