### ISSUE TITLE
Ideas on how to add zeroshot voice cloning ?

### ISSUE THREAD

**Issue by mrakotos** [shivammehta25/Matcha-TTS#127]
Any indication on what should be modified to achieved zero shot tts ?

**Comment by shivammehta25** [comment]
Some speaker representations should be passed (Example: [1](https://huggingface.co/docs/transformers/en/model_doc/wavlm#transformers.WavLMForXVector), [2](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb)). You can find literature on how other architectures do zero-shot voice cloning and then add those speaker representations similarly in the architecture.
