### ISSUE TITLE
what should be the shape of x, x_length, y, y_length at the start of training?

### ISSUE THREAD

**Issue by mrakotos** [shivammehta25/Matcha-TTS#128]
what should be the shape of x, x_length, y, y_length at the start of training?

**Comment by shivammehta25** [comment]
Hello, this is mentioned in the docstrings of the forward function: 

https://github.com/shivammehta25/Matcha-TTS/blob/108906c603fad5055f2649b3fd71d2bbdf222eac/matcha/models/matcha_tts.py#L160-L168
