### ISSUE TITLE
How important is interspersing with 0s text input ?

### ISSUE THREAD

**Issue by theodorblackbird** [shivammehta25/Matcha-TTS#22]
Congrats for your great model ! 
Out of curiosity, how important is interspersing with 0s the text input ?
Is it for extra performance or a crucial design choice ?

**Comment by ghenter** [comment]
My understanding is that interleaving blank tokens is not essential, but generally improves output quality.

The basic effect is that it breaks each phoneme into two separate pieces (beginning and end). This is reasonable based on experience from classic TTS paradigms (we discuss that in [our neural HMM TTS paper](https://arxiv.org/abs/2108.13320)) and conceptually especially relevant for sounds such as [plosives](https://en.wikipedia.org/wiki/Plosive) (which are a stop followed by a burst).

In practice, my impression is that adding blank tokens has become standard in neural TTS nowadays as well. I believe that I first learnt about this strategy from [the Glow-TTS update notes on GitHub](https://github.com/jaywalnut310/glow-tts#update-notes). They also provide examples of the effect it has.

**Comment by theodorblackbird** [comment]
It makes sense for me now, thank you for sharing this.
