### ISSUE TITLE
Are other languages supported？like chinese

### ISSUE THREAD

**Issue by lonngxiang** [shivammehta25/Matcha-TTS#30]

**Comment by ghenter** [comment]
Our users have successfully applied Matcha-TTS to languages such as Hindi (cf. issue #23), so the answer to your question is more "yes" than "no". However, being university researchers, the support provided by us authors is limited: we do not currently provide pre-trained models in other languages and you will have to set things up yourself. There can be useful information regarding how to do that among previously resolved issues (e.g., #9), and @shivammehta25 might be able to help if you get stuck.

**Comment by shivammehta25** [comment]
Hello! @lonngxiang 

Thank you for your question, [we've already answered this question in the past. Please find the answer here.](https://github.com/shivammehta25/Matcha-TTS/issues/9#issuecomment-1735132324).

If you have any further questions please feel free to reopen the issue and continue with the discussions.
