### ISSUE TITLE
Ryanspeech

### ISSUE THREAD

**Issue by francqz31** [shivammehta25/Matcha-TTS#36]
Hey by any chance do you have the Ryanspeech Dataset ?? i have been looking for it for a while and when i apply for the dataset i get an error , so i thought to ask if you can reupload it in case you have it.

Thanks in advance.

**Comment by ghenter** [comment]
Hi there,

The [RyanSpeech license](http://mohammadmahoor.com/ryanspeech-request-form/) contains the following clause:

> 4- Researcher shall not provide the database either partially or as a whole to second parties.

My understanding is that this means that we would violate the license we agreed to if we were to "reupload" the data as requested. Therefore we will not do so unless shown compelling evidence that this reading is incorrect.
