### ISSUE TITLE
Matcha-TTS access denied

### ISSUE THREAD

**Issue by manimator-code** [shivammehta25/Matcha-TTS#41]
I'm getting this error in colab:

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1enuxmfslZciWGAl63WGh2ekVo00FYuQ9

**Comment by shivammehta25** [comment]
This looks like some error with the google drive's permission the hf space is also crashed because of this! Let me see what should be done to fix it. Strange that it just appeared out of the blue.

**Comment by shivammehta25** [comment]
Update: Seems to be an issue with [gDown](https://github.com/wkentaro/gdown/issues/43).

**Comment by shivammehta25** [comment]
Fixed! You will need to update `matcha-tts` you can do a `pip install -U matcha-tts` for fixing it. [Huggingface's space](https://huggingface.co/spaces/shivammehta25/Matcha-TTS) is also up and running!
