### ISSUE TITLE
what should be the maximum duration of the sound?

### ISSUE THREAD

**Issue by Bektemir2001** [shivammehta25/Matcha-TTS#47]

**Comment by Bektemir2001** [comment]
what should be the maximum duration of the sound?

**Comment by shivammehta25** [comment]
There isn't any limitation on the duration of audio, whatever fits in your GPU is the upper bound.

**Comment by shivammehta25** [comment]
Hopefully, your question have been answered, I am closing this issue for now, feel free to reopen it incase you have further questions.
