### ISSUE TITLE
Keeps on running into segfault

### ISSUE THREAD

**Issue by marmikcfc** [shivammehta25/Matcha-TTS#5]
Hey, thanks for open sourcing the model! Would love to experiment with it but whenever I try running it on Amazon Linux 2. Double checked that all the packages are at same versions as requirements.txt. 

Output
```
[ec2-user@ip-172-31-72-8 ~]$ matcha-tts --text "hello world"
[+] GPU Available! Using GPU
[!] Configurations: 
	- Model: matcha_ljspeech
	- Vocoder: hifigan_T2_v1
	- Temperature: 0.667
	- Speaking rate: 0.95
	- Number of ODE steps: 10
	- Speaker: None
[!] Loading matcha_ljspeech!
[+] matcha_ljspeech loaded!
[!] Loading hifigan_T2_v1!
Removing weight norm...
[+] hifigan_T2_v1 loaded!
====================================================================================================
[1] - Input text: hello world
Segmentation fault
```

**Comment by shivammehta25** [comment]
Ah! The good old segfault, I don't really know what is the reason behind it, maybe CUDA drivers mismatch or something? Can you confirm if you encounter this even when you pass the `--cpu` flag?

**Comment by marmikcfc** [comment]
I had tried with the cpu flag and it had caused segfault too.

This is my CUDA version/drivers. I'll try downgrading them today and see if it works. 
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
```

To reproduce you can try using any of the AWS default deep learning AMI on g5 or g4dn instances. I tried with multiple of those instances yesterday and it all resulted in the same segfault.

**Comment by shivammehta25** [comment]
If it is causing a segfault on the CPU too, then it is probably not a CUDA version issue, I have these versions of the torch and its libraries.
```
pytorch-lightning==2.0.8
torch==2.0.1
torchaudio==2.0.2
torchcde==0.2.5
torchdiffeq==0.2.3
torchmetrics==1.1.1
torchsde==0.2.5
torchvision==0.15.2
```

**Comment by shivammehta25** [comment]
Also, a very distant shot in the dark, do you think this might help? https://github.com/pytorch/pytorch/issues/66782#issuecomment-1231372957

**Comment by shivammehta25** [comment]
Did you manage to fix this?

**Comment by shivammehta25** [comment]
Since it was not an issue because of 🍵 Matcha-TTS. I am closing it for now, feel free to reopen incase you have some further questions.
