### ISSUE TITLE
What parameters could you suggest to tweak to improve model perfomance?

### ISSUE THREAD

**Issue by Subuday** [shivammehta25/Matcha-TTS#52]
Hi, I try to train your model on my personal datasets.

Are there any parameters you could suggest to tweak during training on my dataset? Or default params are enough for good quality results?

Are there any specific requirements to a dataset? I have the dataset of similar size like LJSpeech, 22050Hz, mono, similar duration distribution.

**Comment by shivammehta25** [comment]
Hey! 

Thank you for your interest in 🍵 Matcha-TTS. 

> Are there any parameters you could suggest to tweak during training on my dataset? Or default params are enough for good quality results?

It should work just fine with the default parameters, but I've noticed that you can improve quality by adding more parameters to the decoder. 
https://github.com/shivammehta25/Matcha-TTS/blob/256adc55d3219053d2d086db3f9bd9a4bde96fb1/configs/model/decoder/default.yaml#L1-L3

Something like channel 512, 512 and 128 attention dim.

>Are there any specific requirements to a dataset? I have the dataset of similar size like LJSpeech, 22050Hz, mono, similar duration distribution.

This seems to be good enough.

**Comment by Subuday** [comment]
Thanks for your reply!

**Comment by Subuday** [comment]
Thanks for your reply!
