### ISSUE TITLE
Inference is not deterministic?

### ISSUE THREAD

**Issue by orenstuf** [shivammehta25/Matcha-TTS#54]
For the same text I get different WAV files. I run the following command twice:

python cli.py --model matcha_ljspeech --vocoder hifigan_T2_v1 --cpu --output_folder "C:\Project 5 Support\matcha-tts\audio\pytorch-infer" --text "I haven't seen you for a while."

I have attached the two WAV files.

[audio.zip](https://github.com/shivammehta25/Matcha-TTS/files/14229622/audio.zip)

For comparing I have used windows fc command and a hex editor. Difference starts at position 2C.

**Comment by shivammehta25** [comment]
Hello,

Thank you for your interest in 🍵 Matcha-TTS. 

Conditional Flow Matching (CFM) is a probabilistic framework, the first thing we do while sampling is to sample random noise 
https://github.com/shivammehta25/Matcha-TTS/blob/256adc55d3219053d2d086db3f9bd9a4bde96fb1/matcha/models/components/flow_matching.py#L51

Thus resulting in different realisations, quite similar to the generation of multiple images in stable diffusion with the same text by setting different seeds. 

Hope this helps :)

**Comment by orenstuf** [comment]
Hi,

Thank you and sorry for the late respond (I thought that Github will send me an email when I have a respond, but it didn't).

I thought of saving all random values to a file, and load them each time I start my app.
Do you think that this is a good solution? I have found that random values are also used in matcha_tts.py, denoiser.py, and meldataset.py.

**Comment by shivammehta25** [comment]
I think you can also try setting the random seed to a fixed value every time you generate `lightning.seed_everything(1234)`, generally that works. 
But I have never aimed for not having this randomness, I am not so sure about it.

**Comment by orenstuf** [comment]
Ok, Thank you!
