### ISSUE TITLE
Conformer and Time Embeddings

### ISSUE THREAD

**Issue by Subuday** [shivammehta25/Matcha-TTS#58]
Why when Conformer is used, time embeddings are not incorporated?

**Comment by shivammehta25** [comment]
Hello! 

The conformer there was only experimental and was not used in the experiments or the paper. I only left it there to give an example in case somebody wants to switch it with something else (ex. Conformer, Mamba, RWKV etc. or whatever comes in 
the future) 

 I think you can modify how the timestep is added to the hidden states manually if you want to fix it. 

Regards,
Shivam

**Comment by Subuday** [comment]
Thanks.
