### ISSUE TITLE
ONNX Export

### ISSUE THREAD

**Issue by mush42** [shivammehta25/Matcha-TTS#6]
Hi,

Any plans to enable `ONNX` export for `Matcha TTS`?

I developed a script to do it, but it has some issues. Specifically, dynamic shape for `input` is not possible. And synthesis parameters, such as `temperature`, cannot be passed as scalars.

To properly enable ONNX export, we need to change how some tensor and scalar parameters are handled.

Are you interested in ONNX export? If so, how I should proceed? Perhaps with a PR?

Best
Musharraf

**Comment by shivammehta25** [comment]
Maybe just having a script in utils that enables export would be super cool PR. Might be useful for other people as well. I personally have not worked with ONNX. So I might not be a big help there, but would love to read about it and try to help. 

Also why ONNX and not something like Torchscript (which can handle dynamic shapes as much as I understand)?

**Comment by mush42** [comment]
To start with, ONNX is optimized for inference, and works fluently cross-platforms. It can even run inference on the browser, optionally accelerated with web-GPU API.
For neural TTS models, my experience with two different TTS systems shows that onnxruntime is 2x-3x faster than torch, and significantly faster than torch script.
For undevice inference, onnx has an excellent deployment story as demonstrated by [Piper TTS](https://rhasspy.github.io/piper-samples/)

* Note: onnx is an open standard, and omnxruntime is is the defacto runtime for onnx.

**Comment by mush42** [comment]
And also, onnx handles dynamic shapes alright, but the way some layer in Matcha are called makes it harder for the onnx exporter to infer input/output shapes.

**Comment by shivammehta25** [comment]
Ah! Thanks for the clarification, unfortunately, I haven't worked with it. So I might not be able to lead the PR around it. But if you would be willing to help, we can try solving it together. :D

**Comment by mush42** [comment]
Let's do this 😀
