### ISSUE TITLE
[error] git clone

### ISSUE THREAD

**Issue by guitarj** [shivammehta25/Matcha-TTS#61]
I encountered an issue while trying to clone the repository using the git clone command. The error message I received is as follows:

Cloning into 'Matcha-TTS'...
remote: Enumerating objects: 855, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (101/101), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 2925 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

This error occurred on a server running Ubuntu.

**Comment by shivammehta25** [comment]
Hello! This seems to be a `git` error, not the error from repository. Some troubleshooting steps are mentioned in this https://github.com/orgs/community/discussions/48568 . Hopefully that will help!

**Comment by shivammehta25** [comment]
Further, I tried cloning it on collab, seems to be cloning alright. https://colab.research.google.com/drive/1PIPRYQABD66f6yPG0v3bRVgV5i6JQdle?usp=sharing

**Comment by guitarj** [comment]
It works, thank you very much!
:)
