### ISSUE TITLE
how did you choose sigma_min?

### ISSUE THREAD

**Issue by seastar105** [shivammehta25/Matcha-TTS#68]
in [p-flow tts paper](https://openreview.net/pdf?id=zNA7u7wtIN), they choose sigma_min as 0.01, and here use 0.0001

i'm also applying flow matching for tts based on p-flow. is there any reason to choose sigma_min as 1e-4?

**Comment by shivammehta25** [comment]
Actually, I did not do a hyperparameter tuning of it, you can try both :) In theory, since we want the Gaussian to sit at individual data points and then learn that vector field I tried a small sigma which worked just fine. 
But if you do find some differences let me know :) 

Regards,
Shivam
