### ISSUE TITLE
No matching distribution found for piper-phonemize 

### ISSUE THREAD

**Issue by RuslanSel** [shivammehta25/Matcha-TTS#69]
Hi!
I'm trying to install Matcha-TTS from source.
pip install -e .
gives
INFO: pip is looking at multiple versions of matcha-tts to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10                                       
ERROR: Could not find a version that satisfies the requirement piper-phonemize (from matcha-tts) (from versions: none)          
ERROR: No matching distribution found for piper-phonemize 
Thanks in advance.

**Comment by shivammehta25** [comment]
It seems that the piper-phonemize's package is broken, you can remove it from requirements.txt and its import here

https://github.com/shivammehta25/Matcha-TTS/blob/dd9105b34bf2be2230f4aa1e4769fb586a3c824e/matcha/text/cleaners.py#L18

And it should be fine, it was optional anyways. I will remove it in the next versions.

**Comment by RuslanSel** [comment]
Thank you.
