### ISSUE TITLE
Could not create monotonic_align

### ISSUE THREAD

**Issue by lism13** [shivammehta25/Matcha-TTS#7]
Hi. Thanks for sharing the source code.
I tried to train the model with my custom dataset, but the error occurred. Can you help me?

`error: could not create 'matcha/utils/monotonic_align/core.cpython-38-x86_64-linux-gnu.so': No such file or directory                          
`
Best,

**Comment by shivammehta25** [comment]
Hi, 
First, you need to install the source code because the monotonic alignments require Cython and should be compiled first. So run `pip install -e .`  inside the directory, this will setup the requirements and install the monotonic alignment.

**Comment by shivammehta25** [comment]
Also, thank you for opening the issue, I forgot to mention this in the readme. I've updated the README.md with this information, under installation from the source.

**Comment by shivammehta25** [comment]
Can you confirm if it worked? So I can close the issue :D

**Comment by shivammehta25** [comment]
I am closing it for now. Reopen it if it the problem still exists :)
