### ISSUE TITLE
What is the format of train.txt?

### ISSUE THREAD

**Issue by zhaojingxin123** [shivammehta25/Matcha-TTS#83]
What is the format of train.txt? Can you give some examples，thank you。

**Comment by shivammehta25** [comment]
train.txt is same as https://github.com/NVIDIA/tacotron2/blob/master/filelists/ljs_audio_text_train_filelist.txt
val.txt is same as https://github.com/NVIDIA/tacotron2/blob/master/filelists/ljs_audio_text_val_filelist.txt

**Comment by zhaojingxin123** [comment]
Sorry, it is not very convenient to log in to foreign networks in China. I am sorry for missing your explanation.
