### ISSUE TITLE
Can I train with a Mandarin Chinese data set?

### ISSUE THREAD

**Issue by zhaojingxin123** [shivammehta25/Matcha-TTS#86]
Can I train with a Mandarin Chinese data set? What format should the data be in

**Comment by shivammehta25** [comment]
Hello, 

I have tried to summarise how to train it on a different dataset in the wiki here: 
https://github.com/shivammehta25/Matcha-TTS/wiki/Training-%F0%9F%8D%B5-Matcha%E2%80%90TTS-with-different-dataset-&-languages
 
Please see the link above :) Let me know if you have any questions or require any clarification. Feel free to reopen in case of questions.

**Comment by zhaojingxin123** [comment]
感谢大佬的回答，我使用中文数据集 合成出来的都是噪音，感觉可能是因为我的对中文数据集做的音素化处理和symbols使用的不对。我正在修改，数据的输入方式，再重新训练。
Thanks for the big man's （in Chinese it means Superman or handsome man ）answer. All the data I use in Chinese data collection are noise, which may be due to my incorrect phonemization processing and use of symbols in Chinese data set.I use Chinese data set to train and synthesize all the noises, which may be because of my incorrect phonemization processing and use of symbols in Chinese data set. I'm modifying the data input and retraining.
