### ISSUE TITLE
Vocoder training

### ISSUE THREAD

**Issue by sankar-mukherjee** [shivammehta25/Matcha-TTS#87]
Thank you for sharing this nice work. 

I have a question. 

Do i have to train the hifigan from scratch or i can use may be pretrained hifigan from nvidia ngc ? If this true then do i have to change audio processing parameters to match hifigan?

**Comment by shivammehta25** [comment]
Just add ckpt_path
'python matcha_tts/train.py ckpt_path=<PATH>'

**Comment by shivammehta25** [comment]
I've used the pretrained one from HiFiGAN repo, if its any different with audio parameters then I will suggest changing the parameters to match the vocoder's parameters.

**Comment by sankar-mukherjee** [comment]
Thank you for clarification on both issues. 
Another question, can i finetune a pretrained model with small amount of data with this repo? Where should i put the pretrained model path?

**Comment by shivammehta25** [comment]
Just change the filelist location in dataset and resume training with ckpt_path

**Comment by shivammehta25** [comment]
I am closing this for now, feel free to reopen incase of further questions.
