### ISSUE TITLE
diffusers dependency

### ISSUE THREAD

**Issue by frostyplanet** [shivammehta25/Matcha-TTS#88]
Please do not bind specified diffusers version,  lead to pip dep resolve conflict with other library that requires newer version of diffusers

```
xinference[audio,embedding,image,rerank,transformers,vllm] 0+unknown depends on diffusers>=0.29.0; extra == "image"
deepcache 0.1.0 depends on diffusers 
matcha-tts 0.0.6.0 depends on diffusers==0.25.0
xinference[audio,embedding,image,rerank,transformers,vllm] 0+unknown depends on diffusers>=0.29.0; extra == "image"
deepcache 0.1.0 depends on diffusers
matcha-tts 0.0.5.1 depends on diffusers==0.25.0
```

**Comment by shivammehta25** [comment]
Hello, 
I have bound the version because of reproducibility, in case someone wants to reproduce, they can go to the previous tag and use the source code from there. Feel free to remove it as long as it works for you.

**Comment by shivammehta25** [comment]
Done!
I uploaded it to pypy as well future: `pip install -U matcha-tts` should not include the fixed diffusion version of matcha tts. 

PyPi: https://pypi.org/project/matcha-tts
Binaries: https://github.com/shivammehta25/Matcha-TTS/releases/tag/v0.0.7
Commit: https://github.com/shivammehta25/Matcha-TTS/commit/77804265f877b0c42f13cfdece6541dde7838090
