### ISSUE TITLE
Is it possible not fixing version of  `diffusers`

### ISSUE THREAD

**Issue by qinxuye** [shivammehta25/Matcha-TTS#92]
Now the `diffusers` is fixed to 0.25.0, is it possible to remove the limit? This will cause a lot of conflict.

**Comment by shivammehta25** [comment]
I think you can remove the versioning and everything should work. I will do some testing and remove the versioning.

**Comment by qinxuye** [comment]
Thanks, our package relies on Motcha-TTS and diffusers, many models benefits from new version of diffusers, really appreciate you can remove the versioning, we would be more easy on the conflicts of dependencies.

**Comment by shivammehta25** [comment]
Done!
I uploaded it to pypy as well future: `pip install -U matcha-tts` should not include the fixed diffusion version of matcha tts. 

PyPi: https://pypi.org/project/matcha-tts
Binaries: https://github.com/shivammehta25/Matcha-TTS/releases/tag/v0.0.7
Commit: https://github.com/shivammehta25/Matcha-TTS/commit/77804265f877b0c42f13cfdece6541dde7838090
