### ISSUE TITLE
fine-tune on small single speaker datsaet

### ISSUE THREAD

**Issue by yygg678** [shivammehta25/Matcha-TTS#95]
Good work! Pre-train on the multispeaker dataset, then i fine-tune on a small single speaker datsaet. But, i found the synthesized speech a bit robotic. Is there any trick to fine-tune it?

**Comment by shivammehta25** [comment]
Could you please try playing around with the denoising strength here? 

https://github.com/shivammehta25/Matcha-TTS/blob/77804265f877b0c42f13cfdece6541dde7838090/matcha/cli.py#L120

**Comment by yygg678** [comment]
> Could you please try playing around with the denoising strength here?
> 
> https://github.com/shivammehta25/Matcha-TTS/blob/77804265f877b0c42f13cfdece6541dde7838090/matcha/cli.py#L120

Thanks! I found that the high-frequency information in the synthesized speech is lost. Is there a good solution?

**Comment by shivammehta25** [comment]
No, I am sorry, I am not sure what could be the reason.
